name: Auto Merge

on:
  workflow_run:
    types:
      - completed
    workflows:
      - "Update AFFiNE Canary Cask"

jobs:
  merge-me:
    name: Merge me!
    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        if: ${{ github.event.workflow_run.conclusion == 'success' && github.actor == 'github-actions[bot]' }}
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
