name: Auto Merge

on:
  workflow_run:
    workflows: ["Update AFFiNE Canary Cask"]
    types:
      - completed

jobs:
  merge-me:
    name: Merge me!
    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        run: gh pr merge --merge 
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
